(function(c,b){var a="Telerik.OData.ItemsUrl",f="$callback",e="application/json",d={0:"json",1:"jsonp"};
c.NavigationControlODataSettings=function(h){c.NavigationControlODataSettings.initializeBase(this,[h]);
var g=h.ODataSettings;
this._path=h.Path;
this._odata=true;
this._responseType=g.ResponseType;
if(!this.get_isEmpty()){this._tree=new c.ODataBinderTree(g.InitialContainerName,g.Entities,g.EntityContainer);
}};
c.NavigationControlODataSettings.prototype={get_path:function(){return this._path;
},get_responseType:function(){return this._responseType;
},get_tree:function(){return this._tree;
},get_isEmpty:function(){var g=this._odata;
return this._path==""||(g.InitialContainerName==""||g.Entities>0);
}};
c.NavigationControlODataSettings.registerClass("Telerik.Web.UI.NavigationControlODataSettings",c.WebServiceSettings);
c.ODataBinderTree=function(h,i,g){this._entities=i;
this._map=g;
this._loaded=false;
this._tree=this._buildTree(h);
};
c.ODataBinderTree.prototype={get_settingsByDepth:function(g){function h(j,i){if(j==g){return i;
}return h(++j,i.child);
}return h(0,this._tree);
},_buildTree:function(h){var g=!!h?this._getEntitySetByName(h):this._map[0];
return this._buildNode(g,this._findChildCallback);
},_findChildCallback:function(h){if(!h){return;
}var g=this._getEntitySetByName(h);
return this._buildNode(g,this._findChildCallback);
},_buildNode:function(g,k){var j=this._getEntityByName(g.Name),h=this,i={name:g.Name,type:g.EntityType,entity:j,child:k.apply(h,[j.NavigationProperty])};
return i;
},_getByName:function(k,h){for(var j=0;
j<k.length;
j++){var g=k[j];
if(g.Name===h){return g;
}}},_getEntityByName:function(g){return this._getByName(this._entities,this._getEntitySetByName(g).EntityType);
},_getEntitySetByName:function(g){return this._getByName(this._map,g);
}};
c.NavigationControlODataLoader=function(h,g){c.NavigationControlODataLoader.initializeBase(this,[h]);
if(g){this._expandCallback=g;
}else{this._expandCallback=function(){return -1;
};
}};
c.NavigationControlODataLoader.prototype={_createRootUrl:function(h,g){if(h[h.length-1]=="/"){page=h.slice(0,h.length-1);
}return h+"/"+g;
},_getDefferedItemsUrl:function(h){var g=h.get_attributes();
var i=g.getAttribute(a);
g.removeAttribute(a);
return i;
},_appendQueryStringParameters:function(g){return g+"/?$format=json";
},_getAjaxSettings:function(h){h=this._appendQueryStringParameters(h);
var g=this.get_webServiceSettings();
return{url:h,headers:{Accepts:e},dataType:d[g.get_responseType()],jsonp:f};
},get_expandCallback:function(){return this._expandCallback;
},loadData:function(k,m){var j=this.get_webServiceSettings(),h,i,g=false,l=j.get_tree();
if(j.get_isEmpty()){return;
}if(k.isRootLevel){h=l.get_settingsByDepth(0);
i=this._getAjaxSettings(this._createRootUrl(j.get_path(),h.name));
}else{i=this._getAjaxSettings(this._getDefferedItemsUrl(m)),level=m.get_level()+1,h=j.get_tree().get_settingsByDepth(level);
g=true;
}this._sendAjaxRequest(i,m,h.entity,this._onWebServiceSuccess);
if(g){this._raiseEvent("loadingStarted",new Telerik.Web.UI.WebServiceLoaderEventArgs(m));
}},_sendAjaxRequest:function(h,l,g,k){var i=this,j=b.ajax(h);
j.fail(function(n){var m={get_message:function(){return n.statusText;
}};
i._onWebServiceError(m,l);
}).done(function(o){var n=[],m=i._sanitize(o);
b.each(m,function(q,p){n[n.length]={Text:p[g.DataTextField],Value:p[g.DataValueField],ExpandMode:i.get_expandCallback()(g.NavigationProperty),Attributes:(function(){if(g.NavigationProperty&&p[g.NavigationProperty]){return{"Telerik.OData.ItemsUrl":p[g.NavigationProperty].__deferred.uri};
}else{return{};
}})()};
});
k.apply(i,[n,l]);
});
},_sanitize:function(g){var h=g.d.results?g.d.results:g.d;
if(!(h instanceof Array)){h=b.makeArray(h);
}return h;
}};
c.NavigationControlODataLoader.registerClass("Telerik.Web.UI.NavigationControlODataLoader",c.WebServiceLoader);
})(Telerik.Web.UI,$telerik.$);
