Type.registerNamespace("Telerik.Web");
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.ModalExtender=function(a){this._windowResizeDelegate=null;
this._windowScrollDelegate=null;
this._xCoordinate=-1;
this._yCoordinate=-1;
this._backgroundElement=null;
this._foregroundElement=a;
this._saveTabIndexes=new Array();
this._saveDesableSelect=new Array();
this._tagWithTabIndex=new Array("A","AREA","BUTTON","INPUT","OBJECT","SELECT","TEXTAREA","IFRAME");
};
Telerik.Web.UI.ModalExtender.prototype={dispose:function(){this.hide();
this._backgroundElement=null;
this._foregroundElement=null;
},show:function(){var b=this._getModalOverlay();
if($telerik.getVisible(b)){return;
}this._attachWindowHandlers(true);
var a=this._foregroundElement;
a.parentNode.appendChild(b);
var c=$telerik.getCurrentStyle(a,"zIndex");
if(!isNaN(parseInt(c))){b.style.zIndex=c-1;
}b.style.display="";
this._disableTab();
this._updatePageLayout();
this._updatePageLayout();
},_storeBrowserPosition:function(){var b=document.body;
var a=document.documentElement;
this._browserTop=b.scrollTop>a.scrollTop?b.scrollTop:a.scrollTop;
this._browserLeft=b.scrollLeft>a.scrollLeft?b.scrollTop:a.scrollLeft;
},_restoreBrowserPosition:function(d,e){try{if(null==d){d=this._browserLeft;
}if(null==e){e=this._browserTop;
}var b=document.body;
var c=document.documentElement;
b.scrollTop=e;
b.scrollLeft=d;
c.scrollTop=e;
c.scrollLeft=d;
}catch(a){}},hide:function(){this._restoreTab();
this._attachWindowHandlers(false);
var a=this._backgroundElement;
if(a){if(a.parentNode){a.parentNode.removeChild(a);
}this._backgroundElement=null;
}},_enableScroll:function(a){if(a){document.body.style.overflow=null!=this._overflow?this._overflow:"";
document.documentElement.style.overflow=null!=this._documentOverflow?this._documentOverflow:"";
document.body.style.marginRight="";
}else{this._overflow=document.body.style.overflow;
document.body.style.overflow="hidden";
this._documentOverflow=document.documentElement.style.overflow;
document.documentElement.style.overflow="hidden";
document.body.style.marginRight="18px";
}},_getModalOverlay:function(){if(!this._backgroundElement){var a=document.createElement("div");
a.style.display="none";
a.style.position="absolute";
if($telerik.isRightToLeft(this._foregroundElement)){a.style.right="0px";
}else{a.style.left="0px";
}a.style.top="0px";
a.style.zIndex=10000;
a.style.backgroundColor="#aaaaaa";
a.style.filter="progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=50)";
a.style.opacity=".5";
a.style.MozOpacity=".5";
a.setAttribute("unselectable","on");
a.className="TelerikModalOverlay";
this._backgroundElement=a;
}return this._backgroundElement;
},_attachWindowHandlers:function(a){var b=window;
if(true==a){this._windowResizeDelegate=Function.createDelegate(this,this._updatePageLayout);
$addHandler(b,"resize",this._windowResizeDelegate);
this._windowScrollDelegate=Function.createDelegate(this,this._updatePageLayout);
$addHandler(b,"scroll",this._windowScrollDelegate);
}else{if(this._windowResizeDelegate){$removeHandler(b,"resize",this._windowResizeDelegate);
}this._windowResizeDelegate=null;
if(this._windowScrollDelegate){$removeHandler(b,"scroll",this._windowScrollDelegate);
}this._windowScrollDelegate=null;
}},_updatePageLayout:function(){var f=(document.documentElement.scrollLeft?$telerik.getCorrectScrollLeft(document.documentElement):$telerik.getCorrectScrollLeft(document.body));
var a=(document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop);
var e=$telerik.getClientBounds();
var c=e.width;
var b=e.height;
var d=this._getModalOverlay();
d.style.width=Math.max(Math.max(document.documentElement.scrollWidth,document.body.scrollWidth),c)+"px";
d.style.height=Math.max(Math.max(document.documentElement.scrollHeight,document.body.scrollHeight),b)+"px";
},_disableTab:function(){var f=0;
var a;
var e=new Array();
Array.clear(this._saveTabIndexes);
for(var d=0;
d<this._tagWithTabIndex.length;
d++){a=this._foregroundElement.getElementsByTagName(this._tagWithTabIndex[d]);
for(var c=0;
c<a.length;
c++){var b=a[c];
e[f]={tag:b,index:b.tabIndex};
f++;
}}f=0;
for(var d=0;
d<this._tagWithTabIndex.length;
d++){a=document.getElementsByTagName(this._tagWithTabIndex[d]);
for(var c=0;
c<a.length;
c++){var b=a[c];
this._saveTabIndexes[f]={tag:b,index:b.tabIndex};
a[c].tabIndex="-1";
f++;
}}for(var f=0;
f<e.length;
f++){e[f].tag.tabIndex=e[f].index;
}f=0;
if((Sys.Browser.agent===Sys.Browser.InternetExplorer)&&(Sys.Browser.version<7)){var g=new Array();
for(var d=0;
d<this._tagWithTabIndex.length;
d++){a=this._foregroundElement.getElementsByTagName("SELECT");
for(var c=0;
c<a.length;
c++){g[f]=a[c];
f++;
}}f=0;
Array.clear(this._saveDesableSelect);
a=document.getElementsByTagName("SELECT");
for(var c=0;
c<a.length;
c++){if(Array.indexOf(g,a[c])==-1){this._saveDesableSelect[f]={tag:a[c],visib:$telerik.getCurrentStyle(a[c],"visibility")};
a[c].style.visibility="hidden";
f++;
}}}},_restoreTab:function(){for(var a=0;
a<this._saveTabIndexes.length;
a++){this._saveTabIndexes[a].tag.tabIndex=this._saveTabIndexes[a].index;
}if((Sys.Browser.agent===Sys.Browser.InternetExplorer)&&(Sys.Browser.version<7)){for(var b=0;
b<this._saveDesableSelect.length;
b++){this._saveDesableSelect[b].tag.style.visibility=this._saveDesableSelect[b].visib;
}}}};
Telerik.Web.UI.ModalExtender.registerClass("Telerik.Web.UI.ModalExtender",null);
Type.registerNamespace("Telerik.Web");
Telerik.Web.PositioningMode=function(){throw Error.invalidOperation();
};
Telerik.Web.PositioningMode.prototype={Absolute:0,Center:1,BottomLeft:2,BottomRight:3,TopLeft:4,TopRight:5};
Telerik.Web.PositioningMode.registerEnum("Telerik.Web.PositioningMode");
Telerik.Web.PopupBehavior=function(a){Telerik.Web.PopupBehavior.initializeBase(this,[a]);
this._x=0;
this._y=0;
this._positioningMode=Telerik.Web.PositioningMode.Absolute;
this._parentElement=null;
this._parentElementID=null;
this._moveHandler=null;
this._firstPopup=true;
this._originalParent=null;
this._overlay=false;
this._keepInScreenBounds=true;
this._manageVisibility=true;
};
Telerik.Web.PopupBehavior._ie6pinnedList={};
Telerik.Web.PopupBehavior.prototype={getPageOffset:function(){var a={x:($telerik.getCorrectScrollLeft(document.documentElement)||$telerik.getCorrectScrollLeft(document.body)),y:(document.documentElement.scrollTop||document.body.scrollTop)};
return a;
},pin:function(c){var d=this.get_elementToShow();
var b=this.getPageOffset();
if($telerik.isIE6){var a=this.get_id();
if(c){if(Telerik.Web.PopupBehavior._ie6pinnedList[a]){return;
}var e=$telerik.getBounds(d);
Telerik.Web.PopupBehavior._ie6pinnedList[a]=window.setInterval(Function.createDelegate(this,function(){var j=this.getPageOffset();
var h=e.x-b.x+j.x;
var i=e.y-b.y+j.y;
if(this.get_x()==h&&this.get_y()==i){return;
}var k=this.get_parentElement();
this.set_parentElement(document.documentElement);
this.set_x(h);
this.set_y(i);
this.show();
this.set_parentElement(k);
}),130);
}else{var f=Telerik.Web.PopupBehavior._ie6pinnedList[a];
if(f){window.clearInterval(f);
}delete Telerik.Web.PopupBehavior._ie6pinnedList[a];
}}else{var g=c?"fixed":"absolute";
if(d.style.position==g){return;
}var e=$telerik.getBounds(d);
if(c&&(b.x||b.y)){this._x=e.x-b.x;
this._y=e.y-b.y;
$telerik.setLocation(d,{x:this._x,y:this._y});
}d.style.position=g;
}},center:function(){var b=this.get_elementToShow();
if(this._manageVisibility){$telerik.setVisible(b,true);
}var d=$telerik.getClientBounds();
var a=$telerik.getBounds(b);
var f=parseInt((d.width-a.width)/2);
var e=parseInt((d.height-a.height)/2);
var c=this.get_parentElement();
this.set_parentElement(document.documentElement);
this.set_x(f);
this.set_y(e);
this.show();
this.set_parentElement(c);
},get_parentElement:function(){if(!this._parentElement&&this._parentElementID){this.set_parentElement($get(this._parentElementID));
Sys.Debug.assert(this._parentElement!=null,String.format('Couldn\'t find parent element "{0}"',this._parentElementID));
}return this._parentElement;
},set_parentElement:function(a){this._parentElement=a;
},get_parentElementID:function(){if(this._parentElement){return this._parentElement.id;
}return this._parentElementID;
},set_parentElementID:function(a){this._parentElementID=a;
if(this.get_isInitialized()){this.set_parentElement($get(a));
}},get_positioningMode:function(){return this._positioningMode;
},set_positioningMode:function(a){this._positioningMode=a;
},get_x:function(){return this._x;
},set_x:function(a){if(a!=this._x){this._x=a;
if($telerik.getVisible(this.get_elementToShow())&&this._manageVisibility){this.show();
}}},get_y:function(){return this._y;
},set_y:function(a){if(a!=this._y){this._y=a;
if($telerik.getVisible(this.get_elementToShow())&&this._manageVisibility){this.show();
}}},get_overlay:function(){return this._overlay;
},set_overlay:function(c){this._overlay=c;
this._attachWindowHandlers(false);
if(this._overlay){this._attachWindowHandlers(true);
}else{if(!((Sys.Browser.agent===Sys.Browser.InternetExplorer)&&(Sys.Browser.version<7))){var a=this.get_elementToShow();
var b=a._hideWindowedElementsIFrame;
if(b){b.style.display="none";
}}}},get_manageVisibility:function(){return this._manageVisibility;
},set_manageVisibility:function(a){this._manageVisibility=a;
},get_keepInScreenBounds:function(){return this._keepInScreenBounds;
},set_keepInScreenBounds:function(a){this._keepInScreenBounds=a;
},get_elementToShow:function(){return this._elementToShow?this._elementToShow:this.get_element();
},set_elementToShow:function(a){if(this._elementToShow){this._detachElementToShow();
}this._elementToShow=a;
},_detachElementToShow:function(){var c=this.get_elementToShow();
if(this._moveHandler){$telerik.removeExternalHandler(c,"move",this._moveHandler);
this._moveHandler=null;
}var a=c._hideWindowedElementsIFrame;
if(a){var b=a.parentNode;
var d=a.nextSibling;
if(b){b.removeChild(a);
if(d){b.insertBefore(document.createElement("span"),d);
}else{b.appendChild(document.createElement("span"));
}}}},hide:function(){var a=this.get_elementToShow();
if(this._manageVisibility){$telerik.setVisible(a,false);
}if(a.originalWidth){a.style.width=a.originalWidth+"px";
a.originalWidth=null;
}if(Sys.Browser.agent===Sys.Browser.InternetExplorer||this._overlay){var b=a._hideWindowedElementsIFrame;
if(b){b.style.display="none";
}}},show:function(){var a=this.get_elementToShow();
a.style.position="absolute";
var k=document.documentElement;
if($telerik.isFirefox){var g=$telerik.getCurrentStyle(k,"overflow");
if("hidden"==g){a.style.left=k.scrollLeft+"px";
a.style.top=k.scrollLeft+"px";
}}var h=this._manageVisibility;
if(h){$telerik.setVisible(a,true);
}var e=a.offsetParent||k;
if(h){$telerik.setVisible(a,false);
}var b;
var l;
if(this._parentElement){l=$telerik.getBounds(this._parentElement);
var f=this._getOffsetParentLocation(e);
b={x:l.x-f.x,y:l.y-f.y};
}else{l=$telerik.getBounds(e);
b={x:0,y:0};
}if(h){$telerik.setVisible(a,true);
}var j=a.offsetWidth-(a.clientLeft?a.clientLeft*2:0);
var d=a.offsetHeight-(a.clientTop?a.clientTop*2:0);
var c;
switch(this._positioningMode){case Telerik.Web.PositioningMode.Center:c={x:Math.round(l.width/2-j/2),y:Math.round(l.height/2-d/2)};
break;
case Telerik.Web.PositioningMode.BottomLeft:c={x:0,y:l.height};
break;
case Telerik.Web.PositioningMode.BottomRight:c={x:l.width-j,y:l.height};
break;
case Telerik.Web.PositioningMode.TopLeft:c={x:0,y:-a.offsetHeight};
break;
case Telerik.Web.PositioningMode.TopRight:c={x:l.width-j,y:-a.offsetHeight};
break;
default:c={x:0,y:0};
}c.x+=this._x+b.x;
c.y+=this._y+b.y;
$telerik.setLocation(a,c);
if(this._firstPopup){a.style.width=j+"px";
}this._firstPopup=false;
var i=this._fixPositionInBounds();
this._createOverlay(i);
},_getViewportBounds:function(){var b=$telerik.getClientBounds();
var c=document.documentElement;
var a=document.body;
b.scrollLeft=$telerik.isMobileSafari?window.pageXOffset:($telerik.getCorrectScrollLeft(c)||$telerik.getCorrectScrollLeft(a));
b.scrollTop=$telerik.isMobileSafari?window.pageYOffset:(c.scrollTop||a.scrollTop);
return b;
},_getOffsetParentLocation:function(a){if(a&&a.tagName.toUpperCase()!="BODY"&&a.tagName.toUpperCase()!="HTML"){var b=$telerik.getLocation(a);
var c=$telerik.getBorderBox(a);
b.x+=c.top;
b.y+=c.left;
b.x-=$telerik.getCorrectScrollLeft(a);
b.y-=a.scrollTop;
return b;
}return{x:0,y:0};
},_fixPositionInBounds:function(){var b=this.get_elementToShow();
var g=$telerik.getBounds(b);
if(!this._keepInScreenBounds){return g;
}var i=this._getViewportBounds();
var f=false;
var d=(i.width>g.width);
var m=(i.height>g.height);
var k=i.scrollTop;
var j=i.height+k;
var e=i.scrollLeft;
var c=i.width+e;
if(($telerik.isIE8||$telerik.isOpera||$telerik.isSafari)&&$telerik.isRightToLeft(document.body)){var h=b.style.display;
if($telerik.isOpera){b.style.display="none";
}var l=document.documentElement.scrollWidth;
c=l?l:document.body.scrollWidth;
if($telerik.isOpera){b.style.display=h;
}}if(g.x<e||!d){g.x=e;
f=true;
}if(g.y<k||!m){g.y=k;
f=true;
}if(d&&(g.x+g.width>c)){g.x=c-g.width;
f=true;
}if(m&&(j<g.y+g.height)){g.y=j-g.height;
f=true;
}if(f){var a=this._getOffsetParentLocation(b.offsetParent);
g.y-=a.y;
g.x-=a.x;
$telerik.setLocation(b,g);
}return g;
},_createOverlay:function(e){if(!$telerik.isIE6&&!this._overlay){return;
}var a=this.get_elementToShow();
var d=a._hideWindowedElementsIFrame;
if(!d){d=document.createElement("iframe");
d.src="javascript:'<html></html>';";
d.style.position="absolute";
d.style.display="none";
d.scrolling="no";
d.frameBorder="0";
d.tabIndex="-1";
d.style.filter="progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=0)";
a.parentNode.insertBefore(d,a);
a._hideWindowedElementsIFrame=d;
this._moveHandler=Function.createDelegate(this,this._onMove);
$telerik.addExternalHandler(a,"move",this._moveHandler);
}$telerik.setBounds(d,e);
if($telerik.isFirefox){var c=this._getViewportBounds();
d.style.top=parseInt(e.y)-c.scrollTop+"px";
d.style.left=parseInt(e.x)-c.scrollLeft+"px";
d.style.position="fixed";
if($telerik.isFirefox3){d.style.backgroundColor="#fff";
}}if($telerik.quirksMode){return;
}d.style.display=a.style.display;
var b=$telerik.getCurrentStyle(a,"zIndex");
if(b){d.style.zIndex=b;
}},_setCoordinates:function(a,b){var c=false;
if(a!=this._x){this._x=a;
c=true;
}if(b!=this._y){this._y=b;
c=true;
}if($telerik.getVisible(this.get_elementToShow())&&c&&this._manageVisibility){this.show();
}},initialize:function(){Telerik.Web.PopupBehavior.callBaseMethod(this,"initialize");
this.hide();
},dispose:function(){var a=this.get_elementToShow();
if(a){this._attachWindowHandlers(false);
if($telerik.getVisible(a)&&this._manageVisibility){this.hide();
}if(this._originalParent){a.parentNode.removeChild(a);
this._originalParent.appendChild(a);
this._originalParent=null;
}this._detachElementToShow();
}this._parentElement=null;
Telerik.Web.PopupBehavior.callBaseMethod(this,"dispose");
if(a&&a._behaviors&&a._behaviors.length==0){a._behaviors=null;
}a=null;
},_onMove:function(){var c=this.get_elementToShow();
var b=c._hideWindowedElementsIFrame;
if(b){if(Sys.Browser.agent===Sys.Browser.Firefox){var a=this._getViewportBounds();
b.style.top=parseInt(c.style.top)-a.scrollTop+"px";
b.style.left=parseInt(c.style.left)-a.scrollLeft+"px";
b.style.position="fixed";
}else{b.style.top=c.style.top;
b.style.left=c.style.left;
}}},_handleElementResize:function(){var b=this.get_elementToShow();
var a=b._hideWindowedElementsIFrame;
if(a){var c=$telerik.getBounds(b);
$telerik.setBounds(a,c);
}},_attachWindowHandlers:function(a){if(!Sys.Browser.agent===Sys.Browser.Firefox){return;
}var b=window;
if(true==a){this._windowResizeDelegate=Function.createDelegate(this,this._onMove);
$telerik.addExternalHandler(b,"resize",this._windowResizeDelegate);
this._windowScrollDelegate=Function.createDelegate(this,this._onMove);
$telerik.addExternalHandler(b,"scroll",this._windowScrollDelegate);
}else{if(this._windowResizeDelegate){$telerik.removeExternalHandler(b,"resize",this._windowResizeDelegate);
}this._windowResizeDelegate=null;
if(this._windowScrollDelegate){$telerik.removeExternalHandler(b,"scroll",this._windowScrollDelegate);
}this._windowScrollDelegate=null;
}}};
Telerik.Web.PopupBehavior.registerClass("Telerik.Web.PopupBehavior",Sys.UI.Behavior);
Type.registerNamespace("Telerik.Web");
Type.registerNamespace("Telerik.Web.UI");
(function(){var a=$telerik.$;
var b=Telerik.Web.UI;
b.ResizeExtender=function(d,f,e,i,g,c,h,j){this._document=g?g:document;
this._documentMouseMoveDelegate=null;
this._documentMouseUpDelegate=null;
this._jsOwner=null;
this._element=null;
this._tableElement=null;
this._saveDelegates={};
this._moveCursorType="move";
this._moveToMouseLocation=false;
this._hideIframes=true;
this._iframeToSkip=null;
this._enabled=true;
this._startX=0;
this._startY=0;
this._cancelResize=true;
this._startCursorLocation=null;
this._autoScrollEnabled=true;
this.initialize(d,f,e,i,c,h,j);
};
b.ResizeExtender.containsBounds=function(d,g){if(!d||!g){return false;
}var f=$telerik.containsPoint(d,g.x,g.y);
if(f){var c=g.x+g.width;
var e=g.y+g.height;
f=$telerik.containsPoint(d,c,e);
}return f;
};
b.ResizeExtender.prototype={initialize:function(d,h,c,g,e,f,i){if(!h){return;
}if(this._element){alert("Element "+h.getAttribute("id")+" cannot be made resizable, as the resizeExtender already has the element "+this._element.getAttribute("id")+" associated with it. You must create a new extender resizer object");
return;
}this._jsOwner=d;
this._element=h;
this._tableElement=g;
this._handles=c;
if(e){this._moveCursorType=e;
}if(f!=null){this._autoScrollEnabled=f;
}if(i!=null){this._moveToMouseLocation=i;
}this._configureHandleElements(true);
},dispose:function(){this._attachDocumentHandlers(false);
this._configureHandleElements(false);
this._startCursorLocation=null;
this._iframeToSkip=null;
this._jsOwner=null;
this._element=null;
this._handles=null;
this._saveDelegates=null;
this._constraints=null;
},enable:function(c){this._enabled=c;
},set_hideIframes:function(c){this._hideIframes=c;
},get_hideIframes:function(){return this._hideIframes;
},set_iframeToSkip:function(c){this._iframeToSkip=c;
},get_iframeToSkip:function(){return this._iframeToSkip;
},get_constraints:function(){return this._constraints;
},set_constraints:function(c){this._constraints=c;
},get_useCssTransform:function(){return this._useCssTransform;
},set_useCssTransform:function(c){this._useCssTransform=c;
},_raiseDragEvent:function(c,g,e){var d=this._jsOwner;
if(d&&d["on"+c]){var f=g;
if(!f){f={};
}f.element=this._element;
f.ownerEvent=e;
return d["on"+c](f);
}return true;
},_raiseEvent:function(c,e){var d=this._jsOwner;
if(d&&d["on"+c]){if(!e){e=new Sys.EventArgs();
}else{if(c=="Resize"){e=this._resizeDir;
}else{if(c=="Resizing"){e=this._getProposedBounds(e);
}}}return d["on"+c](e);
}return true;
},_getProposedBounds:function(c){var d=$telerik.getBounds(this._element);
return{x:c.x||d.x,y:c.y||d.y,width:c.width||d.width,height:c.height||d.height};
},getPositionedParent:function(){var c=this._element.parentNode;
while(c&&c!=document){if("static"!=$telerik.getCurrentStyle(c,"position","static")){return c;
}c=c.parentNode;
}return null;
},_storeStartCoords:function(d){if(!this._enabled){return;
}this._cancelResize=false;
var h=$telerik.isTouchDevice;
var o=$telerik.getTouchEventLocation(d);
this._startX=h?o.x:d.clientX;
this._startY=h?o.y:d.clientY;
var i=this._element;
var f=$telerik.getBounds(i);
var g=(i.id!=null&&b.RadDock&&b.RadDock.isInstanceOfType($find(i.id)));
if($telerik.isIE&&g!=true){var n=this.getPositionedParent();
if(n){f.x+=n.scrollLeft;
f.y+=n.scrollTop;
}}this._originalBounds=f;
var l=d.target?d.target:d.srcElement;
if(l&&l.type==3){l=l.parentNode;
}this._resizeType=$telerik.getCurrentStyle(l,"cursor");
if(!this._resizeType&&d.currentTarget){this._resizeType=$telerik.getCurrentStyle(d.currentTarget,"cursor");
}this._resizeDir={north:this._resizeType.match(/n.?-/)?1:0,east:this._resizeType.match(/e-/)?1:0,south:this._resizeType.match(/s.?-/)?1:0,west:this._resizeType.match(/w-/)?1:0,move:new RegExp(this._moveCursorType).test(this._resizeType)?1:0};
this._leftHandleMouseDelta=0;
if(this._resizeDir.west){this._leftHandleMouseDelta=Math.abs(f.x-this._startX);
}var c=this._resizeDir.move?this._raiseDragEvent("DragStart",null,d):this._raiseEvent("ResizeStart");
this._cancelResize=(c==false);
var m=$telerik.getCurrentStyle(i.parentNode,"position");
var p=("relative"==m)||("absolute"==m);
this._offsetLocation=p?$telerik.getLocation(i.parentNode):{x:0,y:0};
if(this._moveToMouseLocation){var k=h?{left:this._startX,top:this._startY}:$telerik.getDocumentRelativeCursorPosition({clientX:this._startX,clientY:this._startY});
if(p){var j=$telerik.getBorderBox(i.parentNode);
k.left-=j.left;
k.top-=j.top;
}this._startCursorLocation={x:k.left-Math.floor(f.width/2),y:k.top-Math.floor(f.height/2)};
}if(!this._cancelResize){this._clearSelection();
this._setIframesVisible(false);
this._attachDocumentHandlers(false);
this._attachDocumentHandlers(true);
}},_resize:function(i){if(!this._enabled||this._cancelResize){return false;
}var l=this._originalBounds;
var d=new Sys.UI.Bounds(0,0,0,0);
var m=$telerik.isTouchDevice?$telerik.getTouchEventLocation(i):{x:i.clientX,y:i.clientY};
var g=m.x-this._startX;
var h=m.y-this._startY;
var o=this._resizeDir;
var p=o.move;
if(p){var q=this._startCursorLocation;
if(q){l.x=q.x;
l.y=q.y;
this._originalBounds=l;
this._startCursorLocation=null;
}d.x=l.x+g;
d.y=l.y+h;
var k=this._getMoveConstraints(l);
if(k){d.x=this._constrainPosition(d.x,k.x,k.width);
d.y=this._constrainPosition(d.y,k.y,k.height);
}}else{if(o.east){d.x=l.x;
d.width=l.width+g;
}else{if(o.west){d.x=m.x-this._leftHandleMouseDelta;
d.width=l.width-g;
}}if(o.south){d.y=l.y;
d.height=l.height+h;
}else{if(o.north){d.y=l.y+h;
d.height=l.height-h;
}}var n=this._getSizeConstraints(l);
if(n){d.x=this._constrainPosition(d.x,n.x,Math.min(d.x+d.width,n.width-d.width));
d.y=this._constrainPosition(d.y,n.y,Math.min(d.y+d.height,n.height-d.height));
d.width=this._constrainDimension(d.width,n.width-d.x);
d.height=this._constrainDimension(d.height,n.height-d.y);
}}var c=this._offsetLocation;
if(c){d.x-=c.x;
d.y-=c.y;
}var j=p?this._raiseDragEvent("Drag",d,i):this._raiseEvent("Resizing",d);
if(false==j){return true;
}var f=this._element;
if(this._useCssTransform&&p){this._lastTouchDelta={x:d.x-l.x+c.x,y:d.y-l.y+c.y};
var r={x:d.x?this._lastTouchDelta.x:0,y:d.y?this._lastTouchDelta.y:0};
this._setTranslate(f,r.x,r.y);
}else{if(p||d.x>0){f.style.left=d.x+"px";
}if(p||d.y>0){f.style.top=d.y+"px";
}}if(d.width>0){f.style.width=d.width+"px";
}if(d.height>0){f.style.height=d.height+"px";
}if(!p){this._updateInnerTableSize();
}return true;
},_setTranslate:function(c,f,d){var e=c.style;
e.webkitTransform=e.mozTransform=e.OTransform="translate("+f+"px,"+d+"px)";
},_updateInnerTableSize:function(){var c=this._resizeDir;
if(c.south||c.north){var e=this._element.style.height;
var d=this._tableElement;
if(d){d.style.height=e;
this._fixIeHeight(d,e);
}}},_getMoveConstraints:function(c){var d=this._getSizeConstraints();
if(d){d.width-=c.width;
d.height-=c.height;
}return d;
},_getSizeConstraints:function(d){var c=this._constraints;
if(!c){return null;
}var e=c.x+this._offsetLocation.x;
var f=c.y+this._offsetLocation.y;
return new Sys.UI.Bounds(e,f,e+c.width,f+c.height);
},_constrainPosition:function(e,c,d){return Math.max(c,Math.min(d,e));
},_constrainDimension:function(d,c){return this._constrainPosition(d,0,c);
},_fixIeHeight:function(e,c){if("CSS1Compat"==document.compatMode){var f=(e.offsetHeight-parseInt(c));
if(f>0){var d=(parseInt(e.style.height)-f);
if(d>0){e.style.height=d+"px";
}}}},_setIframesVisible:function(c){if(!this.get_hideIframes()){return;
}var j=this._document.getElementsByTagName("iframe");
var d=this.get_iframeToSkip();
for(var f=0,e=j.length;
f<e;
f++){var g=j[f];
if(d&&(d===g||d==g)){d=null;
}else{g.style.visibility=c?"":"hidden";
if($telerik.isIE){try{g.contentWindow.document.body.style.visibility=c?"":"hidden";
}catch(h){}}}}},_configureHandleElements:function(k){var l=this._handles;
var h=["nw","n","ne","w","e","sw","s","se",this._moveCursorType];
for(var c=0,e=h.length;
c<e;
c++){var g=h[c];
var d=l[g];
if(d){if(Object.prototype.toString.call(d)==="[object Array]"){for(var f=0;
f<d.length;
f++){this._configureHandle("id"+c+"_"+f,k,d[f],g);
}}else{this._configureHandle("id"+c,k,d,g);
}}}},_configureHandle:function(h,e,d,g){var c=this._saveDelegates;
var f=c[h]?c[h].delegate:null;
if(e){if(!f){var i=$telerik.addMobileHandler(this,d,"mousedown",this._onHandleMouseDown,null,true);
d.style.cursor=(g==this._moveCursorType)?g:g+"-resize";
c[h]={element:d,delegate:i};
}}else{if(f){$telerik.removeMobileHandler(d,"mousedown",f,null,true);
d.style.cursor="";
delete c[h];
}}},_attachDocumentHandlers:function(d){var e=this._document;
if(d){this._documentMouseMoveDelegate=$telerik.addMobileHandler(this,e,"mousemove",this._onDocumentMouseMove,null,true);
this._documentMouseUpDelegate=$telerik.addMobileHandler(this,e,"mouseup",this._onDocumentMouseUp,null,true);
}else{var c=this._documentMouseMoveDelegate;
if(c){$telerik.removeMobileHandler(e,"mousemove",c,null,true);
}var f=this._documentMouseUpDelegate;
if(f){$telerik.removeMobileHandler(e,"mouseup",f,null,true);
}this._documentMouseMoveDelegate=null;
this._documentMouseUpDelegate=null;
}},_onHandleMouseDown:function(c){if($telerik.isTouchDevice&&c.originalEvent.touches.length>1){return true;
}this._storeStartCoords(c);
if(!$telerik.isTouchDevice){return $telerik.cancelRawEvent(c);
}},_onDocumentMouseMove:function(c){var d=this._resize(c);
if(this._autoScrollEnabled){this._autoScroll(c);
}if(d){return $telerik.cancelRawEvent(c);
}},_onDocumentMouseUp:function(c){var d=!this._cancelResize;
this._cancelResize=true;
this._startCursorLocation=null;
var f=this._resizeDir&&this._resizeDir.move;
if(this._useCssTransform&&f){this._moveBoxBy(this._lastTouchDelta);
}if(d){this._clearSelection();
this._setIframesVisible(true);
if(f){this._raiseDragEvent("DragEnd",null,c);
}else{this._raiseEvent("ResizeEnd");
}this._attachDocumentHandlers(false);
if(this._scroller){this._scroller.set_enabled(false);
}}},_moveBoxBy:function(e,f){var f=f||this._element;
var d=this._originalBounds;
var c=this._offsetLocation;
boxStartPos=d;
this._resetBoxTransform(f);
f.style.left=boxStartPos.x+e.x-c.x+"px";
f.style.top=boxStartPos.y+e.y-c.y+"px";
},_resetBoxTransform:function(c){var d=c.style;
d.webkitTransform=d.mozTransform=d.OTransform=d.msTranslate="translate(0,0)";
},_clearSelection:function(){if(this._document.selection&&this._document.selection.empty){try{this._document.selection.empty();
}catch(c){}}},_initializeAutoScroll:function(){if(this._autoScrollInitialized){return;
}this._scrollEdgeConst=40;
this._scrollByConst=10;
this._scroller=null;
this._scrollDeltaX=0;
this._scrollDeltaY=0;
this._scrollerTickHandler=Function.createDelegate(this,this._onScrollerTick);
this._scroller=new Telerik.Web.Timer();
this._scroller.set_interval(10);
this._scroller.add_tick(this._scrollerTickHandler);
this._autoScrollInitialized=true;
},_autoScroll:function(c){this._initializeAutoScroll();
var e=$telerik.getClientBounds();
if(e.width>0){this._scrollDeltaX=this._scrollDeltaY=0;
if(c.clientX<e.x+this._scrollEdgeConst){this._scrollDeltaX=-this._scrollByConst;
}else{if(c.clientX>e.width-this._scrollEdgeConst){this._scrollDeltaX=this._scrollByConst;
}}if(c.clientY<e.y+this._scrollEdgeConst){this._scrollDeltaY=-this._scrollByConst;
}else{if(c.clientY>e.height-this._scrollEdgeConst){this._scrollDeltaY=this._scrollByConst;
}}var d=this._scroller;
if(this._scrollDeltaX!=0||this._scrollDeltaY!=0){this._originalStartX=this._startX;
this._originalStartY=this._startY;
d.set_enabled(true);
}else{if(d.get_enabled()){this._startX=this._originalStartX;
this._startY=this._originalStartY;
}d.set_enabled(false);
}}},_onScrollerTick:function(){var e=document.documentElement.scrollLeft||document.body.scrollLeft;
var h=document.documentElement.scrollTop||document.body.scrollTop;
window.scrollBy(this._scrollDeltaX,this._scrollDeltaY);
var k=document.documentElement.scrollLeft||document.body.scrollLeft;
var i=document.documentElement.scrollTop||document.body.scrollTop;
var d=k-e;
var c=i-h;
var f=this._element;
var g={x:parseInt(f.style.left)+d,y:parseInt(f.style.top)+c};
this._startX-=d;
this._startY-=c;
try{$telerik.setLocation(f,g);
}catch(j){}}};
b.ResizeExtender.registerClass("Telerik.Web.UI.ResizeExtender",null,Sys.IDisposable);
})();
